### ISSUE TITLE
[Uninhibited] Create School registration form

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/uninhibited#10]
## Context: 
we will require a school to be registered to attach students as an individual as well as under a group to mark weekly session attendance for all the students.

please refer process flow on this sheet link: https://docs.google.com/spreadsheets/d/1FbHVIISvMqfunwiDBZfwmXeJkIqAnpOwrMWYcZsWcZw/edit#gid=1165697959

School registration form to create: https://docs.google.com/spreadsheets/d/1FbHVIISvMqfunwiDBZfwmXeJkIqAnpOwrMWYcZsWcZw/edit#gid=1210960886

**Comment by Dinesh2019** [comment]
below issues Not required now so closing the card 
- [ ] Name of the surveyor missing this form element or question
- [ ] Number of Girls in the school from 8th std onwards (in the current academic year) missing this question
- [ ] Number of Boys in the school from 9th std onwards (in the current academic year) missing this question
- [ ] Average attendance of Girls in the academic year (give a percentage) missing this question
- [ ] Contact Number of the principal we can remove the phone number validation we can have the regex validation if the cilent doesnt want the verification process for phone number
- [ ] missing this form element Existence of other interventions in the school
- [ ] missing this form element  Logistical Details

**Comment by Dinesh2019** [comment]
When the member is added form the school group it is displayed twice created the bug card in prod 

https://github.com/avniproject/avni-client/issues/1227

**Comment by AnjaliBhagabati** [comment]
This was not delivered in Phase 1, need to complete it in Phase 2

**Comment by pkundu** [comment]
@Parth7223 check whether its really product dependent and lets add this to the Phase 2 Epic
