### ISSUE TITLE
[Uninhibited] Metabase generic monitoring reports

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/uninhibited#15]
List of reports to be created and added to a dashboard on metabase --

- You can refer metabase dashboard as created for Chashma - https://reporting.avniproject.org/dashboard/229-chashma-operational-reports
- Each report should have a drill down to the linelist.

- [x] 1. Number of School audit surveys area wise
- [x] 2. Number of Schools registered area wise
- [x] 3. Number of School Groups registered area wise
- [x] 4. Number of Students registered area wise
- [x] 5. Students without Midline Survey area wise
- [x] 6. Uninhibited users sync telemetry
- [x] point this dashboard to live org (currently this is pointed to UAT
- Uat org: Uninhibited UAT
- live org: periodshala

   -   [Name, username, sync end time, android version, app version,sync source]

**Comment by sachsk** [comment]
Moving this on hold as ETL is not working for this org.
FD: https://avni.freshdesk.com/a/tickets/3383

**Comment by Dinesh2019** [comment]
- [x] Count is mismatched for school count,school group count,student count voided scenario not handled

**Comment by salilsamanvay** [comment]
additional dashboard point added to this card
