### ISSUE TITLE
Periodshala phase 2

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/uninhibited#19]
## Context:
Initially, we were supposed to deliver the midline form by 20th Dec 2023, which has been achieved in phase 1, now we have to deliver the remaining task:

1. Baseline form
2. Endline form
3. Student profile summary page
4. School group creation
5. Weekly attendance form
6. Metabse reports
7. CSV upload

For reference: please go through the previous epic: https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/uninhibited/8

Requirement document: https://docs.google.com/spreadsheets/d/1FbHVIISvMqfunwiDBZfwmXeJkIqAnpOwrMWYcZsWcZw/edit#gid=1165697959

**Comment by salilsamanvay** [comment]
The client is yet to provide the remaining requirements.

**Comment by salilsamanvay** [comment]
@AnjaliBhagabati to schedule call with the Uninhibited team to discuss the remaining requirement.

**Comment by AnjaliBhagabati** [comment]
As per my discussion today with @pkundu we will take this (or any new project) from Next Up, only after all the current Epic In Play cards are closed

**Comment by AnjaliBhagabati** [comment]
As discussed with Salil, scope for Phase 2 are as below:
Baseline form
Endline form
Student profile summary page
School group creation
Weekly attendance form
Pre-menarche form (Done. Delivered in Phase 1)
Metabse reports ( We have given them a few as requested in Phase 1. Phase 2 need to get the requirements from them)
CSV upload
