### ISSUE TITLE
Dashboard requirements for Phase 1 (shared on 10th Jan 2024)

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/uninhibited#21]
The client's dashboard requirement which we were supposed to deliver with the first phase, is given to us now, we will try to complete as much as possible, so that they can monitor the progress of field work. we have already created a dashboard which is very much similar to what they are asking us. need to make changes are per the requirements.

Dashboard created by us: https://reporting.avniproject.org/dashboard/244-monitoring-dashboard

Requirement document: https://docs.google.com/spreadsheets/d/1TJxJzW2Keq6dWh510_OPUAcv90lVRu9_6cIryEjGg40/edit#gid=0

Consider sheet 1 for this card.

- [x] Add date range filter on the dashboard
- [x] add midline survey form submitted count indicator
- [x] add Pre-menarche baseline form submitted count indicator.

**Comment by Dinesh2019** [comment]
- [ ] Date filter is not applied for the midline cards 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnZLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82422ecbfa563e79dc51f3343c1ac89b2d11e114/Screen%20Recording%202024-01-16%20at%209.53.29%E2%80%AFAM.mov

**Comment by sachsk** [comment]
@Dinesh2019 filter is on encounter date time
