### ISSUE TITLE
Uninihibited Phase 1 - Live Environment: Dashboard Issue

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/uninhibited#23]
@sachsk Below is the issue raised by the client:

Issue: Midline datas are not reflecting in app dashboard.
In the live app, the enumerators in Jhabua, namely Anita and Kusum are not able to see the count of their midline surveys done on their dashboards. 

Kindly Refer to the UAT Feedback Sheet shared by the client: https://docs.google.com/spreadsheets/d/1FbHVIISvMqfunwiDBZfwmXeJkIqAnpOwrMWYcZsWcZw/edit#gid=918609632

**Comment by sachsk** [comment]
@AnjaliBhagabati those users dont have the permissions of that encounter please ask clients to give the proper permissions then check the report.

**Comment by sachsk** [comment]
@AnjaliBhagabati those users dont have the permissions of that encounter please ask clients to give the proper permissions then check the report.

**Comment by AnjaliBhagabati** [comment]
Have informed the client and have asked her to give the necessary permission. Waiting for her confirmation. Will close this issue once the client confirms

**Comment by AnjaliBhagabati** [comment]
Closing this as Client confirmed that it is done and working fine now
