### ISSUE TITLE
Uninhibited - Periodshala Phase 1 New Requirement: Metabase Dashboard

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/uninhibited#24]

**Comment by AnjaliBhagabati** [comment]
This is a new request for Metabase (part of Phase 1, which is currently live) that the client has made on our recent call on 29/01/2024.

- The client has requested to add a filter option in the Metabase Dashboard by User_id and Name. 
eg: User_id ( Name)
10103 (Anjali)
The User_id, we can take from the created_by_id, which is currently available on metabase inside each Uninhibited reports. For the Name, currently not showing it in Metabase. 
If adding the name along with the user_id is going to take lot of extra effort, I can inform the client and check if only adding the filter option by User_id will work for them.

Uninihibited Metabase Report Link: https://reporting.avniproject.org/question#eyJuYW1lIjoiQ291bnQgb2YgU3R1ZGVudHMgd2l0aCBtaWRsaW5lIHN1cnZleSIsImRlc2NyaXB0aW9uIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6ImNhcmRfXzI5MTIiLCJmaWx0ZXIiOlsiPSIsWyJmaWVsZCIsIkJsb2NrIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiSmF3aGFyIl19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6MTQwfSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5waXZvdF9jb2x1bW4iOiJCbG9jayIsInRhYmxlLmNlbGxfY29sdW1uIjoiY291bnQifSwib3JpZ2luYWxfY2FyZF9pZCI6MjkxM30=

**Comment by vedfordev** [comment]
@AnjaliBhagabati / @Dinesh2019 we cant't provide userid | username kind of filter. So as username is human readable form we added as filter.
