### ISSUE TITLE
Uninhibited Phase 2: Create a NEW production organisation and then upload bundle from UAT to Prod.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#45]
- [x] Create a new production environment and then upload the bundle from UAT to production. We are not using the old Periodshala production environment
- [x]  Please make sure the below epic changes are tested and moved to production.
- [x] [Epic 1](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/uninhibited/30)

-----
Locations need to be updated with the new hierarchy, such as state, district, and taluk.

[Checklist](https://docs.google.com/document/d/1PPmJpLEyxyh2I2CW4kxmz_EDQcmGp6NjLqRFWM6Hbsk/edit)

[Locations](https://docs.google.com/spreadsheets/d/1gK8uOAaLl2saKiXZ4xlR1ZqFEnSPfeoWJct9AgWLoWE/edit?gid=710572796#gid=710572796)

[User Groups and Permissions](https://docs.google.com/spreadsheets/d/186H_Wv4LS08qKjQBFxKmINe9izSEPyJZdKQrlnRghac/edit?gid=162979324#gid=162979324)

[User Catchment
](https://docs.google.com/spreadsheets/d/1gK8uOAaLl2saKiXZ4xlR1ZqFEnSPfeoWJct9AgWLoWE/edit?gid=224814739#gid=224814739)

### Tech tasks

- [x] Create a new UAT org with Org name - Uninhibited UAT, username suffix - uninhibiteduat
- [x] Create a new org with Org name - Uninhibited, username suffix - uninhibited

Make/Do all the following in UAT first-- 
- [x] Create location hierarchy as in the csv attached
- [x] Exclude locations and location hierarchy from the UAT bundle (since they are different from the actual requirement)
- [x] Then upload the UAT bundle to this new org
- [x] Cross check the subject types and other entities are uploaded properly, and user is able to register a subject with valid address

**Comment by nupoorkhandelwal** [comment]
This cannot be picked up right now, since subject type will fail until we do not have a location hierarchy created.
