### ISSUE TITLE
Uninhibited Phase 2: Visit Schedule

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#48]
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/186H_Wv4LS08qKjQBFxKmINe9izSEPyJZdKQrlnRghac/edit?gid=1107881792#gid=1107881792)

**Comment by Dinesh2019** [comment]
Refrences video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnI1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3beed72740e9733ece214ef6ebbc61dfb8eb58e/My%20Movie.mp4
