### ISSUE TITLE
Uninhibited Phase 2: Creation of user groups and setting up permissions.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#50]
- [x] Create one user group named "Fellow" in UAT.
- [x] Set permissions as in the [sheet](https://docs.google.com/spreadsheets/d/186H_Wv4LS08qKjQBFxKmINe9izSEPyJZdKQrlnRghac/edit?gid=162979324#gid=162979324).

**Comment by Dinesh2019** [comment]
As discussed with Kamesh add the dashboard for both this user group Fellows and Admin
