### ISSUE TITLE
Uninhibited Phase 2: Daily Log

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#65]
- [x] Add this form in UAT.
- [x] This is an unplanned visit to be filled against Subject Name: School. As per the client, this form can be filled out multiple times in a day.
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/186H_Wv4LS08qKjQBFxKmINe9izSEPyJZdKQrlnRghac/edit?gid=1631330695#gid=1631330695)

**Comment by Dinesh2019** [comment]
As per the client this form can be filled multiple times in a day
