### ISSUE TITLE
Uninhibited Phase 2: Enroll in PS 4.1 Period Tracking Program, only when age is greater than or equal to 12.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#66]
- [x] Add a condition to enroll in PS 4.1 Period Tracking Program, only when age is greater than or equal to 12.

**Tech Notes -**
Add program eligibility check rule to achieve this

**Comment by Dinesh2019** [comment]
QA Reference video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjVXQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--708b6c10247c3702e72e38ff5eb2faba98264282/Screen%20Recording%202024-08-14%20at%208.24.14%E2%80%AFAM.mov
