### ISSUE TITLE
Uninhibited Phase 2: Daily Log Report

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#71]
- [x] Reports to be made in UAT in Metabase.
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=1036718167#gid=1036718167)

**Comment by adamsanadi6** [comment]
Dashboard link: [Daily Log](https://reporting.avniproject.org/dashboard/323)

**Comment by sachsk** [comment]
Name of Counsellor is missing in linelist and add data to test

**Comment by Dinesh2019** [comment]
- [ ] description is need to added before prod and UAT
