### ISSUE TITLE
Uninhibited Phase 2: New User Group to be created : Enumerators and Admin

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/uninhibited#75]
- [x] The below to new user groups are to be created in both Uninhibited UAT and Production environment
- [x] Enumerators and Admin. Please refer to [User Groups and Permission sheet](https://docs.google.com/spreadsheets/d/186H_Wv4LS08qKjQBFxKmINe9izSEPyJZdKQrlnRghac/edit?gid=162979324#gid=162979324)
- [x] Admin should not have access to make any changes in App designer

**Comment by adamsanadi6** [comment]
@AnjaliBhagabati In Admin Pannel the following permissions are given:

1. Edit location
2. Edit catchment
3. Edit user configuration
4. Edit language
