### ISSUE TITLE
Period Tracking: 3. Percentage of girls with normal menstrual cycle length

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#79]
- [x]  Report to be made in UAT and in Metabase.
- [x]  [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=2004938207#gid=2004938207&range=51:70)

**Comment by adamsanadi6** [comment]
Dashboard link: [Period Tracking](https://reporting.avniproject.org/dashboard/322)

**Comment by sachsk** [comment]
Code review comment: Report query appears to be incorrect. It should display the total number of registered individuals for percentage calculation, but it currently uses an inner join for enrollment, which only includes individuals who are enrolled in the program.

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.
