### ISSUE TITLE
Period Tracking: 4. Menstrual cycle length of girls

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#80]
- [x]  Report to be made in UAT and in Metabase.
- [x]  [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=2004938207#gid=2004938207&range=72:88)

**Comment by adamsanadi6** [comment]
Dashboard link: [Period Tracking](https://reporting.avniproject.org/dashboard/322)

**Comment by sachsk** [comment]
Code review comment: Report query appears to be incorrect. It should display the total number of registered individuals, but it currently uses an inner join for enrollment, which only includes individuals who are enrolled in the program.

Note: As this reports are on uat so please test report by adding dummy data

**Comment by Dinesh2019** [comment]
QA Refrence video :

[Click here to watch video](https://drive.google.com/file/d/1Q1F7QytQg5czd50tW6he26M1ftr1svXr/view?usp=drive_link)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.
