### ISSUE TITLE
Period Tracking: 6. Pattern and duration of proper bleeding during the most recent menstrual cycle

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#82]
- [x]  Report to be made in UAT and in Metabase.
- [x]  [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=2004938207#gid=2004938207&range=118:145)

**Comment by adamsanadi6** [comment]
Dashboard link: [Period Tracking](https://reporting.avniproject.org/dashboard/322)

**Comment by sachsk** [comment]
@adamsanadi6 as this reports are on UAT please test this report with dummy data

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/11tFVWlBNLaOnzXAKJUEaUTQ9uOw3Q_m-/view?usp=drive_link)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.
