### ISSUE TITLE
1. Pre and Post Programme Comparative Dashboard: Percentage of girls who are aware of what is menstruation

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#85]
- [x] Reports to be made in UAT and in Metabase.
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=14767596#gid=14767596&range=14:33)

**Comment by manish-sd** [comment]
[Dashboard Link](https://reporting.avniproject.org/dashboard/324-pre-and-post-programme-comparative)

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 please fix below in the queries--

- [ ] Move address is voided check in the final where clause, it should not a be join condition

**Comment by dinesh2096** [comment]
test

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal I believe the current logic is optimal, and here’s why:
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVUQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9c57608f91c1e12a4b96b465a964ea150fa97b2/Screenshot%202024-10-01%20at%205.10.56%E2%80%AFPM.png" alt="Screenshot 2024-10-01 at 5.10.56 PM.png" />

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal I believe the current logic is optimal, and here’s why:
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVUQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9c57608f91c1e12a4b96b465a964ea150fa97b2/Screenshot%202024-10-01%20at%205.10.56%E2%80%AFPM.png" alt="Screenshot 2024-10-01 at 5.10.56 PM.png" />

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 Please update the column names as updated in the requirement sheet. @kameshbhariya please highlight whatever change is made in the requirement document.

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.

**Comment by dinesh2096** [comment]
@adam 

- [x] can we show the line list according to the aggregate 
- [x] when we apply date filter count is not matching

**Comment by adamsanadi6** [comment]
@dinesh2096 I have made the same changes to all the other reports as well.

**Comment by dinesh2096** [comment]
- [x] If we applied both the pre and end-program date filter the graph and line list display like the report is empty but we have value for both programs.

**Comment by dinesh2096** [comment]
@kameshbhariya can we add the description that both the date filters are applied at the same time then the count is not displayed graph and line list need to be added for all the reports

**Comment by kameshbhariya** [comment]
@dinesh2096 Description updated.
