### ISSUE TITLE
3. Pre and Post Programme Comparative Dashboard: Percentage of girls who consider menstrual blood to be normal

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#87]
- [x]  Reports to be made in UAT and in Metabase.
- [x]  [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=14767596#gid=14767596&range=58:77)

**Comment by sachsk** [comment]
@manish-sd please add report link

**Comment by manish-sd** [comment]
[Dashboard Link](https://reporting.avniproject.org/dashboard/324-pre-and-post-programme-comparative)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.
