### ISSUE TITLE
6. Pre and Post Programme Comparative Dashboard: Percentage of girls who dried their cloth in the sun

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#90]
- [x] Reports to be made in UAT and in Metabase.
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=14767596#gid=14767596&range=205:205)

**Comment by manish-sd** [comment]
[Dashboard Link](https://reporting.avniproject.org/dashboard/324-pre-and-post-programme-comparative)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.

**Comment by dinesh2096** [comment]
Testing procedure 

- [ ] Create the individual
- [ ] Edit the individual 
- [ ] validate the graph data 
- [ ] validate the x and y axis 
- [ ] validate the graph acording to the indicators
- [ ] validate the count is shown correct in the aggregate and graph 
- [ ] Validate the column all displayed in the report as per the requirement 
- [ ] validate the count aggregate  and line list is matched 
- [ ] Validate the filter with all combination eg : date and age 
- [ ] validate the data after applying all the filters

**Comment by dinesh2096** [comment]
Same issue as card 5
