### ISSUE TITLE
Uninhibited Phase 2: Percentage of girls who called Hello Saathi

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#93]
- [x] Reports to be made in UAT and in Metabase.
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=202325106#gid=202325106)
- [x] Description: This report presents the percentage and details of girls who reached out to the Hello Saathi helpline for support or advice regarding menstruation, indicating their engagement with available resources.

**Comment by manish-sd** [comment]
[Report Collection](https://reporting.avniproject.org/collection/772-girls-who-called-hello-saathi)

**Comment by adamsanadi6** [comment]
[Dashboard link](https://reporting.avniproject.org/dashboard/327)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.
