### ISSUE TITLE
8. Pre and Post Programme Comparative Dashboard: Percentage of girls tracking their periods

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#94]
- [x] Reports to be made in UAT and in Metabase.
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=14767596#gid=14767596&range=279:279)

**Comment by manish-sd** [comment]
[Dashboard Link](https://reporting.avniproject.org/dashboard/324-pre-and-post-programme-comparative)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.

**Comment by dinesh2096** [comment]
@adamsanadi6 the count is not getting capture for pre program
