### ISSUE TITLE
Uninhibited Phase 2: Percentage of girls who visited the local SNEHA clinic post speaking on the hepline.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#95]
- [x] Reports to be made in UAT and in Metabase.
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=435714511#gid=435714511)

**Comment by adamsanadi6** [comment]
[Dashboard link](https://reporting.avniproject.org/dashboard/335)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.
