### ISSUE TITLE
Uninhibited Phase 2: Change in reporting of school attendance post session

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#96]
- [x] Reports to be made in UAT and in Metabase.
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/15gmlRxBRIuXRY5X_GHNkHxtXNFefkdelR-sPTLjYORE/edit?gid=1214694302#gid=1214694302)
- [x] Description: Change in School Attendance Reporting Post-Sessions: This report shows the percentage and details of girls who began attending school more frequently during their periods after attending menstrual health sessions, highlighting the positive impact of educational interventions.

**Comment by adamsanadi6** [comment]
[Dashboard link](https://reporting.avniproject.org/dashboard/331)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal and @kameshbhariya, I have replaced the ‘Out of Range’ filter option with ‘Below 12 & Above 19’ in the Age Category column as well as in the Age Category filter.
