### ISSUE TITLE
Uninhibited Phase 2: User creation and access for Metabase, for Uninhibited reports.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#97]
- [x] Create users for Uninhibited reports in Metabase and provide them with required access.

- [x] [Uninhibited Metabase Dashboards & Reports Access: User & Permissions](https://docs.google.com/spreadsheets/d/1u13TnmQGDGO3tYuxj3ggcCVrc0daHYvZ9BOk4PC9KSs/edit?gid=0#gid=0)

**Comment by adamsanadi6** [comment]
@kameshbhariya User creation is complete. You can test and close the card.
