### ISSUE TITLE
Uninhibited Phase 2: Move dashboards and reports from UAT to production.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/uninhibited#98]
- [x] 1. [Change in Reporting of School Attendance Post Session](https://reporting.avniproject.org/dashboard/331-change-in-reporting-of-school-attendance-post-session)
- [x] 2. [Daily Log](https://reporting.avniproject.org/dashboard/323-daily-log)
- [x] 3. [Girls who called Hello Saathi](https://reporting.avniproject.org/dashboard/327-girls-who-called-hello-saathi)
- [x] 4. [Girls who started Tracking Post the Sessions](https://reporting.avniproject.org/dashboard/326-girls-who-started-tracking-post-the-sessions)
- [x] 5. [Information of girls who visited the local SNEHA Clinic post speaking on the helpline](https://reporting.avniproject.org/dashboard/335-information-of-girls-who-visited-the-local-sneha-clinic-post-speaking-on-the-helpline)
- [x] 6. [Operational Dashboard](https://reporting.avniproject.org/dashboard/320-operational-dashboard?tab=42-sync-telemetry)
- [x] 7. [Period Tracking](https://reporting.avniproject.org/dashboard/322-period-tracking)
- [x] 8. [Pre and Post Programme Comparative](https://reporting.avniproject.org/dashboard/324-pre-and-post-programme-comparative)

**Comment by adamsanadi6** [comment]
@kameshbhariya, all the above listed reports are now pointing to the production DB.
